name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: WebConsole Build with Maven
      run: mvn -B package --file eXperDB-Management-WebConsole/pom.xml
    - name: Management-Agent Resolve Dependency with Maven
      run: mvn -B package --file eXperDB-Management-Agent/pom.xml
    - name: Management-Agent Build with Ant
      run: ant -noinput -buildfile eXperDB-Management-Agent/ant_build/build.xml
    - name: Proxy-Agent Resolve Dependency with Maven
      run: mvn -B package --file eXperDB-Proxy-Agent/pom.xml
    - name: Proxy-Agent Build with Ant
      run: ant -noinput -buildfile eXperDB-Proxy-Agent/ant_build/build.xml